---
version: '3.5'

services:

  flask:
    build: .
    container_name: flask-app
    networks:
      - flaskapi
    env_file:
      - evars.env
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  postgres:
    image: postgres:11
    container_name: postgres-db
    networks:
      - flaskapi
    env_file:
      - evars.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgres

networks:
  flaskapi:
