---
version: '3.5'

services:

  flask:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: flask-app
    env_file:
      - evars.env
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    entrypoint: "dockerize -wait tcp://flask-app-db:5432 -timeout 60s"
    command: ["/bin/bash", "-c", "entrypoint.sh"]

  postgres:
    image: postgres:11
    container_name: flask-app-db
    hostname: flask-app-db
    env_file:
      - evars.env
    ports:
      - "5432:5432"
#    volumes:
#      - ./data:/var/lib/postgres
